services:
  postgres:
    image: postgres:16
    container_name: food_delivery_postgres
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: food_delivery_user
      POSTGRES_PASSWORD: food_delivery_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  redpanda:
    image: redpandadata/redpanda:v24.2.18
    container_name: food_delivery_redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 512M
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644"

volumes:
  postgres_data: