services:
  postgres:
    image: postgres:16
    container_name: food_delivery_postgres
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: food_delivery_user
      POSTGRES_PASSWORD: food_delivery_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
